In [48]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline

In [49]:
df = pd.read_csv("../data/Regression_wine_quality_filtered.csv")

In [50]:
y = df["quality"]
X = df.drop(["quality"], axis=1)

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:
lr = LinearRegression().fit(X_train, y_train)

In [53]:
ridge = Ridge().fit(X_train, y_train)

In [54]:
lasso = Lasso().fit(X_train, y_train)

In [55]:
en = ElasticNet().fit(X_train, y_train)

In [56]:
poly_model = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('regressor', LinearRegression())
])

poly_model.fit(X_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures()),
                ('regressor', LinearRegression())])

In [57]:
models_dict = {
    "Linear": lr,
    "Lasso": lasso,
    "Ridge": ridge,
    "ElasticNet": en,
    "Polynomial": poly_model
}

results = []

for name, model in models_dict.items():
    y_pred = model.predict(X_test)
    
    results.append({
        "Model": name,
        "MSE": mean_squared_error(y_test, y_pred),
        "MAE": mean_absolute_error(y_test, y_pred), 
        "MAPE": mean_absolute_percentage_error(y_test, y_pred),
        "R2": r2_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)
results_df

        Model       MSE       MAE      MAPE        R2
0      Linear  0.387848  0.502137  0.089681  0.406512
1       Lasso  0.647319  0.661857  0.118447  0.009467
2       Ridge  0.391100  0.504458  0.090022  0.401536
3  ElasticNet  0.648317  0.659041  0.117971  0.007940
4  Polynomial  0.387695  0.502717  0.090227  0.406746

In [58]:
param_grid_lr = {'fit_intercept': [True, False], 'copy_X': [True, False]}
lr_optimal = GridSearchCV(LinearRegression(), param_grid_lr, cv=5)
lr_optimal.fit(X_train, y_train)
lr_optimal.best_params_

{'copy_X': True, 'fit_intercept': False}

In [59]:
param_grid_ridge = {
    'alpha': np.arange(0, 1, 0.1),
    'solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sag']
}

ridge_optimal = RandomizedSearchCV(Ridge(), param_grid_ridge).fit(X_train, y_train)
ridge_optimal.fit(X_train, y_train)
ridge_optimal.best_params_

c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Slava\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

{'solver': 'cholesky', 'alpha': np.float64(0.5)}

In [60]:
def objective_en(trial):
    alpha = trial.suggest_float('alpha', 1e-5, 10.0, log=True)
    l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1.0)
    en_optimized = ElasticNet(alpha=alpha, l1_ratio=l1_ratio)
    return cross_val_score(en_optimized, X_train, y_train, cv=5, scoring='r2').mean()

study_en = optuna.create_study(direction='maximize')
study_en.optimize(objective_en, n_trials=50)

en_optimal = ElasticNet(**study_en.best_params)
en_optimal.fit(X_train, y_train)

[I 2026-03-12 18:12:16,503] A new study created in memory with name: no-name-cc7feb2c-4913-4c0e-bd41-35df50f2d2f3
[I 2026-03-12 18:12:16,515] Trial 0 finished with value: 0.3056940497663627 and parameters: {'alpha': 0.013297870418928064, 'l1_ratio': 0.6248671938771843}. Best is trial 0 with value: 0.3056940497663627.
[I 2026-03-12 18:12:16,526] Trial 1 finished with value: 0.2755172092984398 and parameters: {'alpha': 0.09877207272033246, 'l1_ratio': 0.009646389528956134}. Best is trial 0 with value: 0.3056940497663627.
[I 2026-03-12 18:12:16,537] Trial 2 finished with value: 0.32037725615032964 and parameters: {'alpha': 1.395290767121803e-05, 'l1_ratio': 0.48555320922367706}. Best is trial 2 with value: 0.32037725615032964.
[I 2026-03-12 18:12:16,549] Trial 3 finished with value: 0.3205570248158124 and parameters: {'alpha': 0.00023932423180224853, 'l1_ratio': 0.9325985986270586}. Best is trial 3 with value: 0.3205570248158124.
[I 2026-03-12 18:12:16,559] Trial 4 finished with value: 0.02861186977596817 and parameters: {'alpha': 1.1825651475470922, 'l1_ratio': 0.4814519518973922}. Best is trial 3 with value: 0.3205570248158124.
[I 2026-03-12 18:12:16,569] Trial 5 finished with value: 0.17824447935813598 and parameters: {'alpha': 0.2628660098957568, 'l1_ratio': 0.6010894509415514}. Best is trial 3 with value: 0.3205570248158124.
[I 2026-03-12 18:12:16,580] Trial 6 finished with value: 0.3207865301460072 and parameters: {'alpha': 0.0002522839996110233, 'l1_ratio': 0.039462622608808395}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,590] Trial 7 finished with value: 0.027610476425205442 and parameters: {'alpha': 1.1805585685918896, 'l1_ratio': 0.8601950543061864}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,600] Trial 8 finished with value: 0.3205050905657843 and parameters: {'alpha': 6.17566614389589e-05, 'l1_ratio': 0.12142034982600369}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,611] Trial 9 finished with value: 0.027156818508805046 and parameters: {'alpha': 2.702028314692882, 'l1_ratio': 0.42782700301550247}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,623] Trial 10 finished with value: 0.3207018977231931 and parameters: {'alpha': 0.0008143224388276974, 'l1_ratio': 0.24988359057882842}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,635] Trial 11 finished with value: 0.3205984212764072 and parameters: {'alpha': 0.0009904906423529296, 'l1_ratio': 0.21213174472405313}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,647] Trial 12 finished with value: 0.3188548107640229 and parameters: {'alpha': 0.0024686623649629613, 'l1_ratio': 0.2528113748466253}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,658] Trial 13 finished with value: 0.31071021710919766 and parameters: {'alpha': 0.009573870555495839, 'l1_ratio': 0.30813491519706915}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,670] Trial 14 finished with value: 0.32077566841527416 and parameters: {'alpha': 0.0002349694778037866, 'l1_ratio': 0.010009581151029127}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,682] Trial 15 finished with value: 0.3205401521631619 and parameters: {'alpha': 7.461820030858948e-05, 'l1_ratio': 0.00846977935731919}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,694] Trial 16 finished with value: 0.3204001975402228 and parameters: {'alpha': 1.8343881964363006e-05, 'l1_ratio': 0.12252837325337283}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,707] Trial 17 finished with value: 0.32074971796294943 and parameters: {'alpha': 0.000229871059196945, 'l1_ratio': 0.12363412138311394}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,719] Trial 18 finished with value: 0.3132890353202583 and parameters: {'alpha': 0.00618056527084675, 'l1_ratio': 0.35404401559794024}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,731] Trial 19 finished with value: 0.2981546152220229 and parameters: {'alpha': 0.03524848014594417, 'l1_ratio': 0.0006074424127064937}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,743] Trial 20 finished with value: 0.32063010348722487 and parameters: {'alpha': 0.000301107608501208, 'l1_ratio': 0.7741521910166475}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,754] Trial 21 finished with value: 0.32061904083337855 and parameters: {'alpha': 0.00012734886105227476, 'l1_ratio': 0.15164423568488644}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,767] Trial 22 finished with value: 0.3204898383779932 and parameters: {'alpha': 0.0012294087821294517, 'l1_ratio': 0.10206296700315401}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,779] Trial 23 finished with value: 0.3204822077586633 and parameters: {'alpha': 4.978879807708646e-05, 'l1_ratio': 0.07292288115741646}. Best is trial 6 with value: 0.3207865301460072.
[I 2026-03-12 18:12:16,790] Trial 24 finished with value: 0.32083078581533087 and parameters: {'alpha': 0.00041970352129358697, 'l1_ratio': 0.19658078197489065}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,802] Trial 25 finished with value: 0.31750906317096367 and parameters: {'alpha': 0.0037688188169111856, 'l1_ratio': 0.19666886760523805}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,813] Trial 26 finished with value: 0.32076337545709144 and parameters: {'alpha': 0.0005651333553413165, 'l1_ratio': 0.37143664376089414}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,826] Trial 27 finished with value: 0.3204659393560506 and parameters: {'alpha': 4.244544521166119e-05, 'l1_ratio': 0.05862764918656841}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,838] Trial 28 finished with value: 0.3195081047466585 and parameters: {'alpha': 0.002058180599531428, 'l1_ratio': 0.20262691424790427}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,849] Trial 29 finished with value: 0.28026500979662455 and parameters: {'alpha': 0.026640489518651462, 'l1_ratio': 0.7066684200889894}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,863] Trial 30 finished with value: 0.32069952020499987 and parameters: {'alpha': 0.00033047143065440215, 'l1_ratio': 0.5877682761213038}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,875] Trial 31 finished with value: 0.3206960511176816 and parameters: {'alpha': 0.0007089662188502873, 'l1_ratio': 0.38434914435420753}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,887] Trial 32 finished with value: 0.320793162336997 and parameters: {'alpha': 0.0004912782521045315, 'l1_ratio': 0.3257250978468818}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,898] Trial 33 finished with value: 0.3206172916548883 and parameters: {'alpha': 0.00014263828910211378, 'l1_ratio': 0.30374066196145144}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,910] Trial 34 finished with value: 0.3204034698390271 and parameters: {'alpha': 1.928026061489311e-05, 'l1_ratio': 0.05900797696380827}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,922] Trial 35 finished with value: 0.3206093891521288 and parameters: {'alpha': 0.00012227954036948168, 'l1_ratio': 0.16479406595114487}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,934] Trial 36 finished with value: 0.3203683839242989 and parameters: {'alpha': 1.021524511083339e-05, 'l1_ratio': 0.0504175124216967}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,945] Trial 37 finished with value: 0.3207227014726697 and parameters: {'alpha': 0.00040500219430479107, 'l1_ratio': 0.523258703205233}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,957] Trial 38 finished with value: 0.32042134604863154 and parameters: {'alpha': 2.740266215552586e-05, 'l1_ratio': 0.2703715004030908}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,970] Trial 39 finished with value: 0.318712624270773 and parameters: {'alpha': 0.0021507745847215245, 'l1_ratio': 0.4266202069085743}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,981] Trial 40 finished with value: 0.22169588623812747 and parameters: {'alpha': 0.2832047144379103, 'l1_ratio': 0.17155383535313706}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:16,994] Trial 41 finished with value: 0.3207856529464731 and parameters: {'alpha': 0.0004971605047163304, 'l1_ratio': 0.34528367671090265}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:17,006] Trial 42 finished with value: 0.3206329583741682 and parameters: {'alpha': 0.0001553993036068846, 'l1_ratio': 0.30776451303345814}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:17,019] Trial 43 finished with value: 0.32006377628704163 and parameters: {'alpha': 0.0012698988107341564, 'l1_ratio': 0.4577059271107763}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:17,031] Trial 44 finished with value: 0.32048876718088926 and parameters: {'alpha': 7.354064207496948e-05, 'l1_ratio': 0.5341695118866661}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:17,044] Trial 45 finished with value: 0.3205010710869113 and parameters: {'alpha': 0.0005250730307837462, 'l1_ratio': 0.9993500104370008}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:17,055] Trial 46 finished with value: 0.3135982051823847 and parameters: {'alpha': 0.006815192646627833, 'l1_ratio': 0.2740207390489252}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:17,067] Trial 47 finished with value: 0.32070629363834274 and parameters: {'alpha': 0.00020885937687933505, 'l1_ratio': 0.23794035830451532}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:17,078] Trial 48 finished with value: 0.04144809858324474 and parameters: {'alpha': 9.39095753585296, 'l1_ratio': 0.028847853489621416}. Best is trial 24 with value: 0.32083078581533087.
[I 2026-03-12 18:12:17,090] Trial 49 finished with value: 0.3179986267435035 and parameters: {'alpha': 0.003904620097113479, 'l1_ratio': 0.09088540819168467}. Best is trial 24 with value: 0.32083078581533087.

ElasticNet(alpha=0.00041970352129358697, l1_ratio=0.19658078197489065)

In [61]:
def objective_poly(trial):
    degree = trial.suggest_int('degree', 1, 4)
    include_bias = trial.suggest_categorical('include_bias', [True, False])
    model = make_pipeline(PolynomialFeatures(degree=degree, include_bias=include_bias), LinearRegression())
    return cross_val_score(model, X_train, y_train, cv=5, scoring='r2').mean()

study_poly = optuna.create_study(direction='maximize')
study_poly.optimize(objective_poly, n_trials=10)

bp = study_poly.best_params
poly_optimal = make_pipeline(
    PolynomialFeatures(degree=bp['degree'], include_bias=bp['include_bias']), 
    LinearRegression()
)
poly_optimal.fit(X_train, y_train)

[I 2026-03-12 18:12:17,099] A new study created in memory with name: no-name-7c17060a-a449-48bb-ab2e-c7682d5dd2a5
[I 2026-03-12 18:12:17,117] Trial 0 finished with value: 0.31967483102539407 and parameters: {'degree': 1, 'include_bias': True}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:18,240] Trial 1 finished with value: -732.7049144904092 and parameters: {'degree': 4, 'include_bias': False}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:19,372] Trial 2 finished with value: -732.7049144904092 and parameters: {'degree': 4, 'include_bias': False}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:20,505] Trial 3 finished with value: -732.7049144904092 and parameters: {'degree': 4, 'include_bias': False}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:20,547] Trial 4 finished with value: 0.2485251976064072 and parameters: {'degree': 2, 'include_bias': True}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:20,749] Trial 5 finished with value: -1.9021037964609075 and parameters: {'degree': 3, 'include_bias': True}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:20,946] Trial 6 finished with value: -1.9021037964609075 and parameters: {'degree': 3, 'include_bias': True}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:22,074] Trial 7 finished with value: -732.7049144904092 and parameters: {'degree': 4, 'include_bias': False}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:22,309] Trial 8 finished with value: -1.9021037964609075 and parameters: {'degree': 3, 'include_bias': True}. Best is trial 0 with value: 0.31967483102539407.
[I 2026-03-12 18:12:23,431] Trial 9 finished with value: -718.2759074065157 and parameters: {'degree': 4, 'include_bias': True}. Best is trial 0 with value: 0.31967483102539407.

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(degree=1)),
                ('linearregression', LinearRegression())])

In [62]:
def objective_lasso(trial):
    params = {
        'alpha': trial.suggest_float('alpha', 1e-6, 10.0, log=True),
        'selection': trial.suggest_categorical('selection', ['cyclic', 'random'])
    }
    model = Lasso(**params, max_iter=10000)
    
    score = cross_val_score(model, X_train, y_train, cv=5, scoring='r2').mean()
    return score

study_lasso = optuna.create_study(direction='maximize')
study_lasso.optimize(objective_lasso, n_trials=50)

best_lasso_params = study_lasso.best_params
lasso_optimal = Lasso(**best_lasso_params)
lasso_optimal.fit(X_train, y_train)

[I 2026-03-12 18:12:23,442] A new study created in memory with name: no-name-642b380c-8725-4624-b8d0-52a64b1d1238
[I 2026-03-12 18:12:23,453] Trial 0 finished with value: 0.19049523158752535 and parameters: {'alpha': 0.15269660060036822, 'selection': 'random'}. Best is trial 0 with value: 0.19049523158752535.
[I 2026-03-12 18:12:23,465] Trial 1 finished with value: 0.32039289290030676 and parameters: {'alpha': 2.4437986951839407e-05, 'selection': 'random'}. Best is trial 1 with value: 0.32039289290030676.
[I 2026-03-12 18:12:23,475] Trial 2 finished with value: 0.3041151510960421 and parameters: {'alpha': 0.011653064476277588, 'selection': 'cyclic'}. Best is trial 1 with value: 0.32039289290030676.
[I 2026-03-12 18:12:23,486] Trial 3 finished with value: 0.21601685974770257 and parameters: {'alpha': 0.10420840407332768, 'selection': 'cyclic'}. Best is trial 1 with value: 0.32039289290030676.
[I 2026-03-12 18:12:23,497] Trial 4 finished with value: 0.320403865384111 and parameters: {'alpha': 3.599175539270937e-05, 'selection': 'random'}. Best is trial 4 with value: 0.320403865384111.
[I 2026-03-12 18:12:23,508] Trial 5 finished with value: 0.3203858766150722 and parameters: {'alpha': 1.7015660822420268e-05, 'selection': 'random'}. Best is trial 4 with value: 0.320403865384111.
[I 2026-03-12 18:12:23,521] Trial 6 finished with value: 0.31990143403395316 and parameters: {'alpha': 2.3513322970812622e-06, 'selection': 'random'}. Best is trial 4 with value: 0.320403865384111.
[I 2026-03-12 18:12:23,531] Trial 7 finished with value: 0.029039576814993185 and parameters: {'alpha': 0.4589958397453924, 'selection': 'cyclic'}. Best is trial 4 with value: 0.320403865384111.
[I 2026-03-12 18:12:23,541] Trial 8 finished with value: 0.3126656664162725 and parameters: {'alpha': 0.004810179273461076, 'selection': 'cyclic'}. Best is trial 4 with value: 0.320403865384111.
[I 2026-03-12 18:12:23,553] Trial 9 finished with value: 0.31983746850703576 and parameters: {'alpha': 1.7673594448343743e-06, 'selection': 'random'}. Best is trial 4 with value: 0.320403865384111.
[I 2026-03-12 18:12:23,565] Trial 10 finished with value: 0.3205470180786636 and parameters: {'alpha': 0.00027116530671583244, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,576] Trial 11 finished with value: 0.3204561167496357 and parameters: {'alpha': 9.551336999509206e-05, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,588] Trial 12 finished with value: 0.32054583356234556 and parameters: {'alpha': 0.00027379663665724914, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,600] Trial 13 finished with value: 0.32049708381909603 and parameters: {'alpha': 0.0005315521691931649, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,612] Trial 14 finished with value: 0.32048076981572055 and parameters: {'alpha': 0.0005570640238837224, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,623] Trial 15 finished with value: -0.008051906823943212 and parameters: {'alpha': 8.267178906035511, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,635] Trial 16 finished with value: 0.3203740251147192 and parameters: {'alpha': 0.000660455126494914, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,647] Trial 17 finished with value: 0.295201612914832 and parameters: {'alpha': 0.01569152890420627, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,659] Trial 18 finished with value: 0.3204774289672835 and parameters: {'alpha': 0.00012451623238175706, 'selection': 'cyclic'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,671] Trial 19 finished with value: 0.3179435912278358 and parameters: {'alpha': 0.0016490185384605259, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,685] Trial 20 finished with value: 0.3201386388178398 and parameters: {'alpha': 7.249835447756959e-06, 'selection': 'random'}. Best is trial 10 with value: 0.3205470180786636.
[I 2026-03-12 18:12:23,696] Trial 21 finished with value: 0.3205519164895179 and parameters: {'alpha': 0.00033826197444530853, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,707] Trial 22 finished with value: 0.3205046588033235 and parameters: {'alpha': 0.00016637078761857913, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,719] Trial 23 finished with value: 0.3140457795645252 and parameters: {'alpha': 0.002540271260258028, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,731] Trial 24 finished with value: 0.3205293556022667 and parameters: {'alpha': 0.00022501904892404282, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,743] Trial 25 finished with value: 0.32042201305258083 and parameters: {'alpha': 5.529758439688106e-05, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,755] Trial 26 finished with value: 0.32012515228913657 and parameters: {'alpha': 6.960125974413496e-06, 'selection': 'cyclic'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,767] Trial 27 finished with value: 0.2790043510833998 and parameters: {'alpha': 0.021531766463768705, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,779] Trial 28 finished with value: 0.31937246797127516 and parameters: {'alpha': 0.001204089758477297, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,790] Trial 29 finished with value: 0.3125872044538184 and parameters: {'alpha': 0.005000288443906148, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,803] Trial 30 finished with value: 0.32054967634447146 and parameters: {'alpha': 0.00029617264293102367, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,814] Trial 31 finished with value: 0.32051869241462555 and parameters: {'alpha': 0.00019357126652833184, 'selection': 'random'}. Best is trial 21 with value: 0.3205519164895179.
[I 2026-03-12 18:12:23,827] Trial 32 finished with value: 0.32055314239953975 and parameters: {'alpha': 0.00035412271596995, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,841] Trial 33 finished with value: 0.3203835018962941 and parameters: {'alpha': 1.4960538608074276e-05, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,853] Trial 34 finished with value: 0.3204362827788538 and parameters: {'alpha': 7.2129295341625e-05, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,864] Trial 35 finished with value: 0.319613589346042 and parameters: {'alpha': 0.0011027012025261456, 'selection': 'cyclic'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,875] Trial 36 finished with value: 0.23592728609229163 and parameters: {'alpha': 0.045701924924991595, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,888] Trial 37 finished with value: 0.32040015318659526 and parameters: {'alpha': 3.235620952285359e-05, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,899] Trial 38 finished with value: 0.3123964283885573 and parameters: {'alpha': 0.005385455872076639, 'selection': 'cyclic'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,912] Trial 39 finished with value: 0.3205332150111685 and parameters: {'alpha': 0.00045451687518972155, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,924] Trial 40 finished with value: 0.028639560566263378 and parameters: {'alpha': 0.5458083983595708, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,936] Trial 41 finished with value: 0.32054652410146584 and parameters: {'alpha': 0.0002744837204138122, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,949] Trial 42 finished with value: 0.3204411215048384 and parameters: {'alpha': 7.725289620508729e-05, 'selection': 'random'}. Best is trial 32 with value: 0.32055314239953975.
[I 2026-03-12 18:12:23,961] Trial 43 finished with value: 0.3205553832303256 and parameters: {'alpha': 0.000359863740984233, 'selection': 'random'}. Best is trial 43 with value: 0.3205553832303256.
[I 2026-03-12 18:12:23,973] Trial 44 finished with value: 0.3203873255475208 and parameters: {'alpha': 1.8348173597942836e-05, 'selection': 'random'}. Best is trial 43 with value: 0.3205553832303256.
[I 2026-03-12 18:12:23,984] Trial 45 finished with value: 0.3129600707612494 and parameters: {'alpha': 0.0034899066515666683, 'selection': 'random'}. Best is trial 43 with value: 0.3205553832303256.
[I 2026-03-12 18:12:23,996] Trial 46 finished with value: 0.3201111192982273 and parameters: {'alpha': 0.0008283005996635585, 'selection': 'cyclic'}. Best is trial 43 with value: 0.3205553832303256.
[I 2026-03-12 18:12:24,008] Trial 47 finished with value: 0.3204238915187563 and parameters: {'alpha': 5.6979889101693295e-05, 'selection': 'random'}. Best is trial 43 with value: 0.3205553832303256.
[I 2026-03-12 18:12:24,020] Trial 48 finished with value: 0.3205461422215591 and parameters: {'alpha': 0.00041696889168177007, 'selection': 'random'}. Best is trial 43 with value: 0.3205553832303256.
[I 2026-03-12 18:12:24,032] Trial 49 finished with value: 0.3147887365396733 and parameters: {'alpha': 0.0023150129729842136, 'selection': 'random'}. Best is trial 43 with value: 0.3205553832303256.

Lasso(alpha=0.000359863740984233, selection='random')

In [63]:
models_dict = {
    "Linear": lr_optimal,
    "Lasso": lasso_optimal,
    "Ridge": ridge_optimal,
    "ElasticNet": en_optimal,
    "Polynomial": poly_optimal
}

results = []

for name, model in models_dict.items():
    y_pred = model.predict(X_test)
    
    results.append({
        "Model": name,
        "MSE": mean_squared_error(y_test, y_pred),
        "MAE": mean_absolute_error(y_test, y_pred), 
        "MAPE": mean_absolute_percentage_error(y_test, y_pred),
        "R2": r2_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)
results_df

        Model       MSE       MAE      MAPE        R2
0      Linear  0.388853  0.502505  0.089732  0.404974
1       Lasso  0.389872  0.503358  0.089861  0.403414
2       Ridge  0.389853  0.503369  0.089849  0.403444
3  ElasticNet  0.389981  0.503457  0.089864  0.403249
4  Polynomial  0.387848  0.502137  0.089681  0.406512

In [64]:
def get_mae(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

In [65]:
def get_mse(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

In [66]:
def get_rmse(y_true, y_pred):
    return np.sqrt(np.mean((y_true - y_pred)**2))

In [67]:
def get_mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true))

In [68]:
def get_r2(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred)**2)
    ss_tot = np.sum((y_true - np.mean(y_true))**2)
    return 1 - (ss_res / ss_tot)

In [69]:
results = []

for name, model in models_dict.items():
    y_pred = model.predict(X_test)
    
    results.append({
        "Model": name,
        "MSE": mean_squared_error(y_test, y_pred),
        "MAE": mean_absolute_error(y_test, y_pred), 
        "MAPE": mean_absolute_percentage_error(y_test, y_pred),
        "R2": r2_score(y_test, y_pred),
        "Custom MSE": get_mse(y_test, y_pred),
        "Custom MAE": get_mae(y_test, y_pred), 
        "Custom MAPE": get_mape(y_test, y_pred),
        "Custom R2": get_r2(y_test, y_pred)
    })

results_df = pd.DataFrame(results)
results_df

,Model,MSE,MAE,MAPE,R2,Custom MSE,Custom MAE,Custom MAPE,Custom R2
0,Linear,0.388853,0.502505,0.089732,0.404974,0.388853,0.502505,0.089732,0.404974
1,Lasso,0.389872,0.503358,0.089861,0.403414,0.389872,0.503358,0.089861,0.403414
2,Ridge,0.389853,0.503369,0.089849,0.403444,0.389853,0.503369,0.089849,0.403444
3,ElasticNet,0.389981,0.503457,0.089864,0.403249,0.389981,0.503457,0.089864,0.403249
4,Polynomial,0.387848,0.502137,0.089681,0.406512,0.387848,0.502137,0.089681,0.406512

In [70]:
from Lab2_LinearRegression import LinearRegressionSGD

model = LinearRegressionSGD(lr=0.001, epochs=100)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f"MSE: {get_mse(y_test, y_pred):.4f}")
print(f"MAPE: {get_mape(y_test, y_pred):.4f}")
print(f"MAE: {get_mae(y_test, y_pred):.4f}")
print(f"R2 Score: {get_r2(y_test, y_pred):.4f}")

MSE: 0.3935
MAPE: 0.0908
MAE: 0.5075
R2 Score: 0.3978

У всех моделей получились +- схожие метрики. Для моделей Lasso и ElasticNet пришлось подбирать гиперпараметры для улучшения метрик.

Формально лучшей моделью для данной задачи является полиномиальная регрессия, так как у нее меньше ошибка и выше коэффициент R^2.