In [11]:
import pandas as pd

Импорт датасетов из предыдущей лабораторной работы

In [12]:
small_df = pd.read_csv('../Lab2/ID1_S50_F5', sep = ",", encoding="utf-8")
small_df = small_df.drop(small_df.columns[0], axis=1)
large_df = pd.read_csv('../Lab2/ID12_S1500_F15', sep = ",", encoding="utf-8")
large_df = large_df.drop(large_df.columns[0], axis=1)

In [13]:
small_df.head(5)

,Obj1_bin_1,Obj1_nominal_2,Obj1_ordinal_3,Obj1_quantitative_4,Obj1_bin_5,Obj2_bin_1,Obj2_nominal_2,Obj2_ordinal_3,Obj2_quantitative_4,Obj2_bin_5,collision
0,1,1000,1,980.096113,0,0,500,3,977.171355,0,0
1,1,1000,1,62.853585,1,1,777,4,484.041589,1,1
2,1,500,2,106.014272,0,1,777,1,530.112921,1,0
3,1,1000,1,136.243390,1,1,777,1,105.784598,1,1
4,1,500,3,287.653502,1,1,1000,3,624.642187,0,0

In [14]:
large_df.head(5)

,Obj1_bin_1,Obj1_nominal_2,Obj1_ordinal_3,Obj1_quantitative_4,Obj1_bin_5,Obj1_nominal_6,Obj1_ordinal_7,Obj1_quantitative_8,Obj1_bin_9,Obj1_nominal_10,...,Obj2_ordinal_7,Obj2_quantitative_8,Obj2_bin_9,Obj2_nominal_10,Obj2_ordinal_11,Obj2_quantitative_12,Obj2_bin_13,Obj2_nominal_14,Obj2_ordinal_15,collision
0,0,500,2,179.369390,1,1000,1,220.479678,0,777,...,4,808.199044,0,500,3,221.703125,0,500,4,1
1,1,1000,3,186.354031,1,333,1,968.937961,1,500,...,4,630.463153,1,333,2,582.807334,0,333,4,1
2,1,1000,3,377.092703,0,777,3,567.345268,0,777,...,4,226.712704,1,333,2,304.761060,1,1000,4,0
3,1,1000,2,73.033068,0,777,1,855.936203,1,500,...,1,847.582755,0,333,1,340.000172,0,500,4,0
4,0,500,3,523.380040,0,333,2,826.869352,0,333,...,1,911.994991,0,333,4,182.358591,0,333,4,0

Лучшие модели из прошлой лабораторной работы

In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [16]:
best_models = [
    KNeighborsClassifier(),
    RandomForestClassifier()
]

Результаты подбора гиперпараметров из предыдущей лабораторной работы
| Model | Small | Big |
| :--- | :---: | ---: |
| KNeighborsClassifier | 0.610465|2.531045|
| RandomForestClassifier | 4.116801 | 10.344154 |